# The URL the site will be built for
base_url = "https://waffleplug.com"
title = "The Waffle Plug"
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]

[extra]
tagline = "Handcrafted waffles, made with love."
order_form_url = "https://tally.so/r/81OoXx"
instagram_url = "https://instagram.com/coming_soon"
contact_email = "coming_soon@waffleplug.com"
